### ISSUE TITLE
cannot authorize the github api

### ISSUE THREAD

**Issue by Runbo94** [Runbo94/gitgroup-api#1]
Problems occur at 
./lib/models/userModel.ts
./lib/tests/models/userModel.test.ts

I got the GitHub api url from "./config/default.json" and access token from environment variable. But I cannot access GitHub api. So I tried to use postman to access the api, then I get the following error message.

<img width="756" alt="wechat screenshot_20181019173235" src="https://user-images.githubusercontent.com/32821733/47244859-163e4d80-d3c5-11e8-85a7-0181fd2e48e4.png">

**Comment by jasonoochen** [comment]
https://segmentfault.com/a/1190000015144126?utm_source=tag-newest
BIU BIU!

**Comment by jasonoochen** [comment]
CHECK THIS OUT! RUNBO94!

**Comment by wuhxxx** [comment]
![image](https://user-images.githubusercontent.com/16824561/47245944-331c5600-d3b0-11e8-9d9f-f2eae9bdc0ec.png)
What i got is Requires authentication for "/user"

Do you mean "/users"?
![image](https://user-images.githubusercontent.com/16824561/47246074-d1102080-d3b0-11e8-9a5b-820feee9eefb.png)

**Comment by Runbo94** [comment]
> CHECK THIS OUT! RUNBO94!

You are absolutely the guru of api development!

**Comment by Runbo94** [comment]
> ![image](https://user-images.githubusercontent.com/16824561/47245944-331c5600-d3b0-11e8-9d9f-f2eae9bdc0ec.png)
> What i got is Requires authentication for "/user"
> 
> Do you mean "/users"?
> ![image](https://user-images.githubusercontent.com/16824561/47246074-d1102080-d3b0-11e8-9a5b-820feee9eefb.png)
You are genius!
